FROM recognizebv/symfony-docker:php7.2-sf4

RUN pecl install -f xdebug \
    && pecl clear-cache \
    && echo "zend_extension=$(ls /usr/local/lib/php/*/*/xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_enable = On" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart = On" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_connect_back = On" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.coverage_enable = Off" >> /usr/local/etc/php/conf.d/xdebug.ini